#!/bin/bash

options=(
    active_color="glow(0xffca66ff)"
    inactive_color=0x00553355
    width=2.0
    order=above
    hidpi=on
    blacklist=Stickies,"Calculator Plus",Simulator,Emulator,"qemu-system-aarch64","qemu-system-x86-64",universalAccessAuthWarn,coreautha,coreauthd,coreauthagent,coreauthui
)

borders "${options[@]}"
